spring.application.name=scrappi
# Fuerza la zona horaria en la conexión a la DB
spring.datasource.url=jdbc:postgresql://localhost:5433/db_scrappi?serverTimezone=America/Bogota

# Configura Hibernate para que no convierta a UTC
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

# Configura Jackson para que al enviar el JSON al Frontend mantenga la hora local
spring.jackson.time-zone=America/Bogota
